# Generated by Django 5.0 on 2026-01-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='asset',
            name='api_source',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='api_symbol',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='base_currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='price',
            name='value_source',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('currency', 'Devise'), ('commodity', 'Matière première'), ('crypto', 'Crypto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='price',
            name='value_mru',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
    ]
